const fiveLetterWords = [
    "ABOUT", "ABOVE", "AFTER", "AGAIN", "AMONG", "APPLE", "AWARE", "BEACH", "BEARD", "BIRTH",
    "BLACK", "BLOOD", "BOARD", "BRAIN", "BREAK", "BREAD", "BROWN", "BUILD", "CARRY", "CATCH",
    "CAUSE", "CHAIN", "CHAIR", "CHASE", "CHECK", "CHEST", "CHILD", "CLAIM", "CLASS", "CLEAR",
    "CLIMB", "CLOCK", "CLOSE", "COACH", "COAST", "COLOR", "COULD", "COVER", "DANCE", "DEATH",
    "DEPTH", "DOUBT", "DREAM", "DRINK", "DRIVE", "EARTH", "ENEMY", "ENJOY", "ENTER", "EQUAL",
    "EVERY", "FAITH", "FIELD", "FIGHT", "FINAL", "FIRST", "FLOOR", "FOCUS", "FORCE", "FRONT",
    "FRUIT", "GLASS", "GRACE", "GREEN", "GROUP", "GUIDE", "HAPPY", "HEART", "HEAVY", "HORSE",
    "HOUSE", "HUMAN", "LARGE", "LAUGH", "LEAVE", "LIGHT", "LIMIT", "LIVER", "LOCAL", "LUCKY",
    "MATCH", "MEDIA", "METAL", "MONTH", "MUSIC", "NEVER", "OCEAN", "PAINT", "PAPER", "PARTY",
    "PEACE", "POWER", "PRESS", "PRIDE", "PROVE", "QUIET", "RAISE", "REACH", "RIVER", "SCENE"
  ];
  